### ISSUE TITLE
[Request] Add xkcd-font

### ISSUE THREAD

**Issue by phanirithvij2000** [KnotUntied/scoop-fonts#1]
- **URL to font**: https://github.com/ipython/xkcd-font
- **Latest version**: 1.0

**Comment by KnotUntied** [comment]
xkcd-script is fine, but I'm not sure about xkcd or xkcd-Regular for now, with the latter two having different lowercase kerning and [that's it, I guess](https://github.com/ipython/xkcd-font/issues/31). Might have to check the source code and build scripts.

**Comment by KnotUntied** [comment]
Looking at this again, xkcd-Regular seems to be the finished version of xkcd, so I'll add only that variant.
